### ISSUE TITLE
Another NoneType object regarding orderbook

### ISSUE THREAD

**Issue by emperorbullz** [donewiththedollar/directional-scalper#10]
Hi Tyler!

Found this one bug about calling the non-existent order book:
<img width="455" alt="Screen Shot 2023-03-19 at 23 11 27" src="https://user-images.githubusercontent.com/12150704/226189073-8f60912f-3b43-44b1-b08c-996bfe95247f.png">

I am using the version 1.1.0. It's on the bot.py

Thank you

**Comment by donewiththedollar** [comment]
Pushed a possible fix, we will have to wait and see if it works :) thank you for reporting this!

**Comment by ecoppen** [comment]
This one should be being caught with an exception now, probably needs more logging to diagnose similar to #11

**Comment by ecoppen** [comment]
Please reopen if you experience again, log should record the information needed to fix :)
