### ISSUE TITLE
JSON Decode Error

### ISSUE THREAD

**Issue by emperorbullz** [donewiththedollar/directional-scalper#9]
Hi Tyler!

Found an error while running the code.

<img width="721" alt="Screen Shot 2023-03-17 at 11 28 28" src="https://user-images.githubusercontent.com/12150704/225812724-b5fd6325-8fae-4322-af49-9f38483bb781.png">

Looks like because it passed no value, JSON did not decode it

**Comment by donewiththedollar** [comment]
Looking into this :) thank you, this is most likely the final one that still is unhandled properly.

**Comment by emperorbullz** [comment]
Looks like its fixed. Thanks!
